import { Player } from "./player";

export const PLAYERS: Player[] = [
  {
    id: 1,
    firstName: 'Ivan ',
    lastName: 'Curkovic',
    jerseyNumber: 1,
    role: 'GK',
    teamName: 'ASSE',
  },
  {
    id: 2,
    firstName: 'Laurent ',
    lastName: 'Blanc',
    jerseyNumber: 2,
    role: 'DEF',
    teamName: 'ASSE',
  },
  {
    id: 3,
    firstName: 'Michel',
    lastName: 'Platini',
    jerseyNumber: 7,
    role: 'MID',
    teamName: 'ASSE',
  },
  {
    id: 4,
    firstName: 'Pascal',
    lastName: 'Feindouno',
    jerseyNumber: 10,
    role: 'MID',
    teamName: 'ASSE',
  },
  {
    id: 5,
    firstName: 'Dominique',
    lastName: 'Rocheteau',
    jerseyNumber: 11,
    role: 'ATT',
    teamName: 'ASSE',
  },
  {
    id: 6,
    firstName: 'Fabien',
    lastName: 'Barthez',
    jerseyNumber: 16,
    role: 'GK',
    teamName: 'France',
  },
  {
    id: 8,
    firstName: "N'Golo",
    lastName: 'Kante',
    jerseyNumber: 7,
    role: 'MID',
    teamName: 'France',
  },
  {
    id: 9,
    firstName: 'Zinedine',
    lastName: 'Zidane',
    jerseyNumber: 10,
    role: 'MID',
    teamName: 'France',
  },
  {
    id: 10,
    firstName: 'Thierry',
    lastName: 'Henry',
    jerseyNumber: 11,
    role: 'ATT',
    teamName: 'France',
  },
];
